// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCATTs1Vtg2mNdP6uIoNUq1Aptjj9P1Qp0',
    appId: '1:967376222236:web:788112a148e99852f007d9',
    messagingSenderId: '967376222236',
    projectId: 'food-signal',
    authDomain: 'food-signal.firebaseapp.com',
    storageBucket: 'food-signal.appspot.com',
    measurementId: 'G-YD3EPRWS9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7aLdSFxUXlINrtRC-ebhaYqeJsW8b36A',
    appId: '1:967376222236:android:2968d94fe8864b94f007d9',
    messagingSenderId: '967376222236',
    projectId: 'food-signal',
    storageBucket: 'food-signal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVyOwn4M3lV5tvSuAotb15lhpfNvvVVQU',
    appId: '1:967376222236:ios:2a8e009e7d16fbdbf007d9',
    messagingSenderId: '967376222236',
    projectId: 'food-signal',
    storageBucket: 'food-signal.appspot.com',
    iosClientId: '967376222236-mvjfkvqbhndsbpj5bhiqioervl923p3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodSignal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVyOwn4M3lV5tvSuAotb15lhpfNvvVVQU',
    appId: '1:967376222236:ios:86d63aa1d462987ff007d9',
    messagingSenderId: '967376222236',
    projectId: 'food-signal',
    storageBucket: 'food-signal.appspot.com',
    iosClientId: '967376222236-g84h9c86skiue6k4om4v1lmijn3hj0b9.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodSignal.RunnerTests',
  );
}
